### ISSUE TITLE
AttributeError when using DecimalFractionField with ModelAdmin

### ISSUE THREAD

**Issue by febsn** [jmichalicek/django-fractions#5]
I am trying to use django-fractions in a ModelAdmin. When trying to save an instance of a model containing a DecimalFractionField in the admin the following happens:

- When I enter a non-integer fraction and hit save, "This field is required" shows up, as if I hadn't input anything.
- When I enter an integer value, an AttributeError shows up: "'Fraction' object has no attribute 'as_tuple'".

Steps to reproduce: Setup a new project with Django==1.10.4 and django-fractions==0.4.0 on Python 3.4. Create a simple model containing a DecimalFractionField and a ModelAdmin for it. Try to create an instance in the admin.

Is there anything I got wrong, or doesn't django-fractions support the Django Admin site? If this is bug, please let me know I can help to resolve it.

**Comment by jmichalicek** [comment]
I've merged a fix for this into master.  I need to update a few other things in the test and release workflow and then push this out as a 1.0.0 release.  Using a major version bump due to DecimalFractionField no longer subclassing Django's DecimalField, just in case anyone was doing any typechecking.

**Comment by febsn** [comment]
Works like a charm, thanks a ton!
